### ISSUE TITLE
Invalid index in Availability Domains lookup

### ISSUE THREAD

**Issue by moisesdasilvadeoliveira** [oracle-quickstart/oci-cloud-native-sftp#4]
Hey cdvita,

I'm having the same problem this https://github.com/oracle-quickstart/oci-cloud-native-sftp/issues/1

Error OCI
022/06/21 16:09:27 [[INFO]] Terraform has been successfully initialized!
2022/06/21 16:09:27 [[INFO]]
2022/06/21 16:09:27 [[INFO]] You may now begin working with Terraform. Try running "terraform plan" to see
2022/06/21 16:09:27 [[INFO]] any changes that are required for your infrastructure. All Terraform commands
2022/06/21 16:09:27 [[INFO]] should now work.
2022/06/21 16:09:27 [[INFO]]
2022/06/21 16:09:27 [[INFO]] If you ever set or change modules or backend configuration for Terraform,
2022/06/21 16:09:27 [[INFO]] rerun this command to reinitialize your working directory. If you forget, other
2022/06/21 16:09:27 [[INFO]] commands will detect it and remind you to do so if necessary.
2022/06/21 16:09:30 [[INFO]]
**2022/06/21 16:09:30 [[INFO]] Error: Invalid index**
2022/06/21 16:09:30 [[INFO]]
**2022/06/21 16:09:30 [[INFO]] on servers.tf line 21, in resource "oci_core_instance" "cn_sftp_servers"
2022/06/21 16:09:30 [[INFO]] 21: availability_domain = data.oci_identity_availability_domains.ads.availability_domains[count.index % (length(data.oci_identity_availability_domains.ads.availability_domains) - 1)].name**
2022/06/21 16:09:30 [[INFO]] ├────────────────
2022/06/21 16:09:30 [[INFO]] │ count.index is 1
2022/06/21 16:09:30 [[INFO]] │ data.oci_identity_availability_domains.ads.availability_domains is list of object with 1 element

**Terraform Line**
availability_domain = data.oci_identity_availability_domains.ads.availability_domains[count.index % (length(data.oci_identity_availability_domains.ads.availability_domains) - 1)].name

Can you help me? I'm using OCI Resource Manager

**Comment by cdivita** [comment]
Hello, which region are you using ?

**Comment by moisesdasilvadeoliveira** [comment]
Hello

São Paulo

**Comment by moisesdasilvadeoliveira** [comment]
> Hello, which region are you using ?
Hello

Region São_Paulo

**Comment by cdivita** [comment]
In Regions with 1 Availability Domain, the AD lookup failed due to a wrong expression. Such expression worked for Regions with 3 Availability Domains, even if without the intended behaviour.

The issue has been fixed in release [1.3.0](https://github.com/oracle-quickstart/oci-cloud-native-sftp/releases/tag/v1.3.0)
